### PR TITLE
Added additional types and tests

### PR DESCRIPTION
**Pull request by bradbeam**

### CODE REVIEW

**Comment by bradbeam** [comment]
Sorry, had to do a force push because the older commits had my work email in there.

**Comment by bradbeam** [comment]
I did want to call attention to https://github.com/go-chef/gladius/pull/2/files#diff-b280ff48a8f26a50e7dd1d82aaf0755aR186

I found that pretty interesting and am open for suggestions.

**Comment by spheromak** [comment]
@bradbeam  After tonights peer with AJ I think all this is probably no longer relevant,  However I believe we have the right pattern in place now.

**Comment by fujin** [comment]
I'm so sorry :-(

**Pull request closed without merging**
